
bioText = "CGTATATGATGAGGACAAGCAGCGTGAGGACACGTATATGAAGCAGCGCGTATATGATGAGGACAAGCAGCGTGAGGACATGAGGACAGTACTGCCGTATATGACGTATATGAGTACTGCTGAGGACAGTACTGCTCGATAATAGTACTGCCGTATATGATGAGGACACGTATATGATGAGGACAGTACTGCGTACTGCCGTATATGATGAGGACAGTACTGCTGAGGACACGTATATGATGAGGACAGTACTGCTCGATAATAAGCAGCGAGCAGCGTGAGGACAGTACTGCTGAGGACAAGCAGCGTGAGGACATGAGGACAAGCAGCGTCGATAATATGAGGACAAGCAGCGCGTATATGACGTATATGACGTATATGAAGCAGCGCGTATATGATGAGGACAGTACTGCGTACTGCTGAGGACAAGCAGCGAGCAGCGTGAGGACAGTACTGCCGTATATGAGTACTGCGTACTGCTGAGGACACGTATATGATCGATAATAGTACTGCAGCAGCGTGAGGACAAGCAGCGCGTATATGACGTATATGAGTACTGCCGTATATGAGTACTGCTCGATAATATCGATAATACGTATATGAAGCAGCGAGCAGCGCGTATATGATGAGGACAAGCAGCGCGTATATGATCGATAATAAGCAGCGAGCAGCGGTACTGCGTACTGCGTACTGCTGAGGACAAGCAGCGCGTATATGACGTATATGATCGATAATAAGCAGCGTCGATAATAAGCAGCGAGCAGCGAGCAGCGAGCAGCGTCGATAATAAGCAGCGTCGATAATAAGCAGCGTCGATAATAGTACTGCCGTATATGAAGCAGCG"
#bioPattern = "GGGGCACGG"
k = 11


def patternCount(txt, pat):
    count = 0
    for i in range(0,len(txt)-len(pat)+1):
        #print txt[i:i+len(pat)]
        if pat==txt[i:i+len(pat)] :
            count+=1
    return count

from sets import Set
def frequentWords(txt, k):
    kmers = Set()
    frequency = []
    max_occurences = 0
    for i in range(0,len(txt)-k+1):
        pat = txt[i:i+k]
        frequency.append( patternCount(txt, pat) )
        if (frequency[i] >= max_occurences):
            max_occurences = frequency[i]
    
    for i in range(0,len(txt)-k+1):
        if (frequency[i] == max_occurences):
            pat = txt[i:i+k]
            if (pat not in kmers):
                kmers.add(txt[i:i+k])
                print str(frequency[i]) + " : " + txt[i:i+k]
    

frequentWords(bioText, k)
#print patternCount(bioText, bioPattern)